productName: torre-electron-react
appId: fun.junso.bunuelo.torre.electron.react
copyright: junso
directories:
  output: build
# mac:
#   icon: ../build/icon/icon.ico
linux:
  target:
    - AppImage
    - deb
files:
      - node_modues/**/*
      - dist/**/*